/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerInteligenciaArtificial;
import java.awt.event.WindowEvent;
import javax.swing.ButtonGroup;

/**
 *
 * @author josdan
 */
public class ViewConfiguracionAlgoritmo extends javax.swing.JFrame {

    private ControllerInteligenciaArtificial controlador;
    
    
    /**
     * Creates new form ViewConfiguracionAlgoritmo
     */
    public ViewConfiguracionAlgoritmo() {
        
        //jrbMetodoNumeroDeEvoluciones.setSelected(true);
       
        //da error el setSelected
        initComponents();
         
        jrbMetodoNumeroDeEvoluciones.setSelected(true);
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(jrbMetodoNumeroDeEvoluciones);
        grupo.add(jrbMetodoRepetirFitness); 
        jtValorDeRepeticiones.setEditable(false);
        
    }

    public ControllerInteligenciaArtificial getControlador() {
        return controlador;
    }

    public void setControlador(ControllerInteligenciaArtificial controlador) {
        this.controlador = controlador;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtNumeroEvoluciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbCrearConfiguracion = new javax.swing.JButton();
        jbCancelarConfiguracion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jrbMetodoNumeroDeEvoluciones = new javax.swing.JRadioButton();
        jrbMetodoRepetirFitness = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtValorDeRepeticiones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtPorcentajeDeMutacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion del Algoritmo Genetico");

        jLabel1.setText("CONFIGURACION DEL ALGORITMO");

        jtNumeroEvoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumeroEvolucionesActionPerformed(evt);
            }
        });

        jLabel2.setText("Evoluciones");

        jbCrearConfiguracion.setText("Crear");
        jbCrearConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearConfiguracionActionPerformed(evt);
            }
        });

        jbCancelarConfiguracion.setText("Cancelar");
        jbCancelarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarConfiguracionActionPerformed(evt);
            }
        });

        jLabel3.setText("Metodo de corte");

        jrbMetodoNumeroDeEvoluciones.setText("Numero de evoluciones");
        jrbMetodoNumeroDeEvoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbMetodoNumeroDeEvolucionesMouseClicked(evt);
            }
        });
        jrbMetodoNumeroDeEvoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMetodoNumeroDeEvolucionesActionPerformed(evt);
            }
        });

        jrbMetodoRepetirFitness.setText("Repeticion de fitness");
        jrbMetodoRepetirFitness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbMetodoRepetirFitnessMouseClicked(evt);
            }
        });

        jLabel4.setText("Valor de repeticion");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText("Numeros de evoluciones o numeros de repeticiones fitness");

        jtValorDeRepeticiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorDeRepeticionesActionPerformed(evt);
            }
        });

        jLabel6.setText("Parametros de Mutacion");

        jtPorcentajeDeMutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcentajeDeMutacionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setText("Porcentaje de evolucion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelarConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCrearConfiguracion)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jrbMetodoNumeroDeEvoluciones)
                                    .addComponent(jtNumeroEvoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtPorcentajeDeMutacion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtValorDeRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jrbMetodoRepetirFitness)
                                    .addComponent(jLabel4))
                                .addContainerGap(88, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNumeroEvoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMetodoNumeroDeEvoluciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMetodoRepetirFitness)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtValorDeRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPorcentajeDeMutacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCrearConfiguracion)
                    .addComponent(jbCancelarConfiguracion))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNumeroEvolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumeroEvolucionesActionPerformed
        
    }//GEN-LAST:event_jtNumeroEvolucionesActionPerformed

    private void jbCrearConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearConfiguracionActionPerformed
        
                
        //TODO agregar atributos para instanciar la configuracion:
        //tamanio de poblacion
        //metodo de corte
        //valor del metodo
        //porcentaje de mutacion
        controlador.crearConfiguracion();
        
        int cantidadRepeticiones;
        int tipoCorte;
        
        if(jrbMetodoNumeroDeEvoluciones.isSelected() == true){
            tipoCorte = 1;
            cantidadRepeticiones = 0;
        } else {
            tipoCorte = 2;
            cantidadRepeticiones = Integer.valueOf(jtValorDeRepeticiones.getText());
        }
        
        int numeroEvoluciones = Integer.valueOf(jtNumeroEvoluciones.getText());
        int porcentajeMutacion = Integer.valueOf(jtPorcentajeDeMutacion.getText());
        controlador.configurarAlgoritmoGenetico(tipoCorte, numeroEvoluciones,cantidadRepeticiones,porcentajeMutacion );
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jbCrearConfiguracionActionPerformed

    private void jrbMetodoNumeroDeEvolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMetodoNumeroDeEvolucionesActionPerformed
        
    }//GEN-LAST:event_jrbMetodoNumeroDeEvolucionesActionPerformed

    private void jtValorDeRepeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorDeRepeticionesActionPerformed
        
    }//GEN-LAST:event_jtValorDeRepeticionesActionPerformed

    private void jtPorcentajeDeMutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcentajeDeMutacionActionPerformed
        
    }//GEN-LAST:event_jtPorcentajeDeMutacionActionPerformed

    private void jbCancelarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarConfiguracionActionPerformed
        
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        
    }//GEN-LAST:event_jbCancelarConfiguracionActionPerformed

    private void jrbMetodoNumeroDeEvolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbMetodoNumeroDeEvolucionesMouseClicked
    jtValorDeRepeticiones.setEditable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMetodoNumeroDeEvolucionesMouseClicked

    private void jrbMetodoRepetirFitnessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbMetodoRepetirFitnessMouseClicked
    jtValorDeRepeticiones.setEditable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMetodoRepetirFitnessMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracionAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracionAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracionAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracionAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConfiguracionAlgoritmo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbCancelarConfiguracion;
    private javax.swing.JButton jbCrearConfiguracion;
    private javax.swing.JRadioButton jrbMetodoNumeroDeEvoluciones;
    private javax.swing.JRadioButton jrbMetodoRepetirFitness;
    private javax.swing.JTextField jtNumeroEvoluciones;
    private javax.swing.JTextField jtPorcentajeDeMutacion;
    private javax.swing.JTextField jtValorDeRepeticiones;
    // End of variables declaration//GEN-END:variables
}
